name: Terraform Deploy to Azure

on:
  workflow_dispatch:
    inputs:
      APPLY:
        description: '¿Execute terraform apply?'
        required: true
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init with backend config
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ secrets.AZURE_RESOURCE_GROUP }}" \
            -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT }}" \
            -backend-config="container_name=${{ secrets.AZURE_CONTAINER_NAME }}" \
            -backend-config="key=terraform.tfstate"

      - name: Auto format Terraform files
        run: terraform fmt -recursive

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Export Terraform Plan to JSON
        run: terraform show -json tfplan > tfplan.json

      - name: Upload Terraform Plan JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-json
          path: tfplan.json

      - name: Terraform Apply
        if: ${{ github.event.inputs.APPLY == 'true' }}
        run: |
          terraform apply -auto-approve tfplan
          echo "Public IP:"
          terraform output public_ip
