terraform {
  required_version = ">= 0.14"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.1.0"
    }
  }

  backend "azurerm" {}
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "web_cluster_rg" {
  name     = "my-terraform-rg"
  location = "West Europe"
}

resource "azurerm_virtual_network" "web_cluster_vnet" {
  name                = "my-terraform-vnet"
  location            = azurerm_resource_group.web_cluster_rg.location
  resource_group_name = azurerm_resource_group.web_cluster_rg.name
  address_space       = ["10.0.0.0/16"]

  tags = {
    environment = "my-terraform-env"
  }
}

resource "azurerm_subnet" "web_cluster_subnet" {
  name                 = "my-terraform-subnet"
  resource_group_name  = azurerm_resource_group.web_cluster_rg.name
  virtual_network_name = azurerm_virtual_network.web_cluster_vnet.name
  address_prefixes     = ["10.0.2.0/24"]
}

resource "azurerm_public_ip" "web_cluster_public_ip" {
  name                = "my-terraform-public-ip"
  location            = azurerm_resource_group.web_cluster_rg.location
  resource_group_name = azurerm_resource_group.web_cluster_rg.name
  allocation_method   = "Static"

  tags = {
    environment = "my-terraform-env"
  }
}

resource "azurerm_lb" "web_cluster_lb" {
  name                = "my-terraform-lb"
  location            = azurerm_resource_group.web_cluster_rg.location
  resource_group_name = azurerm_resource_group.web_cluster_rg.name

  frontend_ip_configuration {
    name                 = "my-terraform-lb-frontend-ip"
    public_ip_address_id = azurerm_public_ip.web_cluster_public_ip.id
  }

  tags = {
    environmen
